---
title: "Resumo dos projetos"
author: "Gabriela de Paula Gonzalez"
date: "5 de abril de 2018"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Essa página apresenta um resumo dos projetos realizado na disciplina **"Análise de Dados e Introdução à Machine Learning"**.

***

## Projeto 1

* Título: Análise Exploratória de Dados ENEM

### Descrição
Esse projeto tem como objetivo realizar uma análise exploratória no dados relacionados aos dados do ENEM de 2016. O dataset foi retirado de um desafio realizado pela [Code Nation](<https://app.codenation.com.br/acceleration/data-science>). Assim, os dados representam apenas uma amostra dos participantes da prova real.

### Relatório do Projeto

Link no [meu Github](<https://github.com/gabrielapgonzalez>) *Pages*: [Projeto 1](projetos/pjt1_anexp.html)

***

## Projeto 2

* Título: Regressão linear

### Descrição
Projeto com objetivo de prever o preço de uma casa, principalmente pela variável de área.

### Relatório do Projeto

Link no [meu Github](<https://github.com/gabrielapgonzalez>) *Pages*: [Projeto 2](projetos/pjt2_reg.html)

***

## Projeto 3

* Título: Regressão Múltipla

### Descrição
Projeto com objetivo de prever a Demanda por tickets de uma cia aérea considerando dia da semana, mês e se é feriado ou não.

### Relatório do Projeto

Link no [meu Github](<https://github.com/gabrielapgonzalez>) *Pages*: [Projeto 3](projetos/pjt3_regm.html)


***

## Projeto 4

* Título: Decision Tree

### Descrição
Projeto com objetivo de prever características de recém nascidos utilizando decision tree.

### Relatório do Projeto

Link no [meu Github](<https://github.com/gabrielapgonzalez>) *Pages*: [Projeto 3](projetos/pjt4_dtree.html)

***

## Projeto 5

* Título: Regressão Logística

### Descrição
Projeto com objetivo de prever características de recém nascidos utilizando Regressão Logística.

### Relatório do Projeto

Link no [meu Github](<https://github.com/gabrielapgonzalez>) *Pages*: [Projeto 3](projetos/pjt5_rlog.html)


***

## Projeto 6

* Título: KNN

### Descrição
Projeto com objetivo de prever região do vinho utilizando KNN.

### Relatório do Projeto

Link no [meu Github](<https://github.com/gabrielapgonzalez>) *Pages*: [Projeto 3](projetos/pjt6_knn.html)
